spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/lamicons
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8082
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true

# AWS S3 Configuration
aws:
  s3:
    enabled: true
    access-key: 
    secret-key: 
    region: ap-south-1
    bucket-name: 
    prefix: dummy

# File Upload Configuration
file:
  upload:
    max-size: 10MB
    allowed-image-types: image/jpeg,image/png
    allowed-video-types: video/mp4,video/mpeg,video/webm
    allowed-document-types: application/pdf

# Eureka (optional — won't crash if Eureka not running)
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Cloudinary Configuration
cloudinary:
  cloud-name: dcurn2sr2
  api-key: 126865781851976
  api-secret: OPiBXYe7pri7kQ20EBJEIpud8RI

upload:
  max-file-size: 5242880 # 5 MB threshold
