package com.Lamicons.CurriculumService.DTO.Course;

public enum CourseCategory {
    PROGRAMMING,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DEVOPS,
    CLOUD_COMPUTING,
    CYBERSECURITY,
    DATABASES,
    NETWORKING,
    BLOCKCHAIN,
    GAME_DEVELOPMENT,
    UI_UX_DESIGN,
    PROJECT_MANAGEMENT,
    COMPETITIVE_PROGRAMMING,
    BUSSINESS,
    OTHER
}