package com.Lamicons.CurriculumService.Service.impl;

import com.Lamicons.CurriculumService.Service.StorageService;
import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Slf4j
@Service
@Profile({"local", "default"})
public class CloudinaryStorageServiceImpl implements StorageService {

    private final Cloudinary cloudinary;
    
    // Configured for local environment with max file size (e.g. 5MB)
    @Value("${upload.max-file-size:5242880}")
    private long maxFileSize;

    public CloudinaryStorageServiceImpl(
            @Value("${cloudinary.cloud-name}") String cloudName,
            @Value("${cloudinary.api-key}") String apiKey,
            @Value("${cloudinary.api-secret}") String apiSecret) {
        
        this.cloudinary = new Cloudinary(ObjectUtils.asMap(
                "cloud_name", cloudName,
                "api_key", apiKey,
                "api_secret", apiSecret,
                "secure", true
        ));
        log.info("CloudinaryStorageServiceImpl initialized to 'local' profile");
    }

    @Override
    public Map<String, Object> generateUploadSignature(String folderName, String fileName) {
        try {
            long timestamp = System.currentTimeMillis() / 1000L;
            Map<String, Object> paramsToSign = new HashMap<>();
            
            // Basic params for signature
            paramsToSign.put("timestamp", timestamp);
            paramsToSign.put("folder", folderName);
            
            // Enforce file size limits - in Cloudinary this can be done via upload presets or indirectly via signatures if configured properly, but usually enforced at the upload preset stage or client edge. 
            // We can return max_file_size for the client to enforce.
            
            String signature = cloudinary.apiSignRequest(paramsToSign, cloudinary.config.apiSecret);
            
            Map<String, Object> response = new HashMap<>();
            response.put("uploadUrl", "https://api.cloudinary.com/v1_1/" + cloudinary.config.cloudName + "/auto/upload");
            response.put("signature", signature);
            response.put("timestamp", timestamp);
            response.put("folder", folderName);
            response.put("apiKey", cloudinary.config.apiKey);
            response.put("maxFileSize", maxFileSize);
            
            log.info("Generated Cloudinary upload credentials for folder: {}", folderName);
            return response;
        } catch (Exception e) {
            log.error("Failed to generate Cloudinary signature", e);
            throw new RuntimeException("Failed to generate upload signature");
        }
    }

    @Override
    public String getFileUrl(String fileKey) {
        // Cloudinary fileKey is usually the public_id provided post-upload.
        // Or in a direct upload flow, the client gets the full secure_url back.
        // If they just pass key, we return the transformed URL. 
        // We'll assume the URL generated by Cloudinary is simply passed to standard config.
        return cloudinary.url().secure(true).generate(fileKey);
    }
}